### ISSUE TITLE
Error while building on iOS

### ISSUE THREAD

**Issue by cchamikara** [Kalyzee/react-native-gstreamer#23]
I'm getting this error when I build iOS project in Xcode 

~/Library/Developer/GStreamer/iPhone.sdk/GStreamer.framework/Headers/glibconfig.h:6:10: 'x86_64/glibconfig.h' file not found

**Comment by ma6e1** [comment]
hi, if your Xcode version is 10.0+, try replace the header search file to "$(HOME)/Library/Developer/GStreamer/iPhone.sdk/GStreamer.framework/Headers" instead of "~/Library/Developer/GStreamer/iPhone.sdk/GStreamer.framework/Headers".
