### ISSUE TITLE
Why iOS doesn't work?

### ISSUE THREAD

**Issue by whn09** [Kalyzee/react-native-gstreamer#7]
Hello,

I have tried 0.0.5 and the master branch, the plugin doesn't work on iOS.

When I run the master branch, I get the error in the screenshot.

![image](https://user-images.githubusercontent.com/964527/33868647-281368c2-df3f-11e7-8996-267c200cd199.png)

Can you tell me how to run on iOS correctly? Thank you!

**Comment by bavuvanet** [comment]
i think "GstPlayer" available only on Android, ios is: RCTGSTPlayer

**Comment by whn09** [comment]
@bavuvanet 
Can you show me how to use in App.js?

Because I changed GstPlayer to RCTGSTPlayer in App.js, but it doesn't work.

I use 0.0.5 version.

Thank you!

**Comment by alann-sapone** [comment]
Sorry for the late answer.
As you might have noticed, I completely reworked the entire project and it now comes with a detailed documentation on how to use it. Feel free to test this version 2 and keep me aware if anything goes wrong.
